// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJHaX38Ithzjrpnw2pYWXDpjYkFtj2Pes',
    appId: '1:986107011501:web:29478a09c3d59791990124',
    messagingSenderId: '986107011501',
    projectId: 'aafnai-karesabari',
    authDomain: 'aafnai-karesabari.firebaseapp.com',
    databaseURL: 'https://aafnai-karesabari-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aafnai-karesabari.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzB9HOs-RpcBT4p_-aNKzJRM7Ksf-QSp0',
    appId: '1:986107011501:android:8afc37424bca5d31990124',
    messagingSenderId: '986107011501',
    projectId: 'aafnai-karesabari',
    databaseURL: 'https://aafnai-karesabari-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aafnai-karesabari.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJU3jxHCkTFmvxng9JqOzVvTEJMvk1gYE',
    appId: '1:986107011501:ios:8a91e32863d60ffb990124',
    messagingSenderId: '986107011501',
    projectId: 'aafnai-karesabari',
    storageBucket: 'aafnai-karesabari.firebasestorage.app',
    iosBundleId: 'com.example.aafnaiKaresabari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJU3jxHCkTFmvxng9JqOzVvTEJMvk1gYE',
    appId: '1:986107011501:ios:8a91e32863d60ffb990124',
    messagingSenderId: '986107011501',
    projectId: 'aafnai-karesabari',
    storageBucket: 'aafnai-karesabari.firebasestorage.app',
    iosBundleId: 'com.example.aafnaiKaresabari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJHaX38Ithzjrpnw2pYWXDpjYkFtj2Pes',
    appId: '1:986107011501:web:29478a09c3d59791990124',
    messagingSenderId: '986107011501',
    projectId: 'aafnai-karesabari',
    authDomain: 'aafnai-karesabari.firebaseapp.com',
    storageBucket: 'aafnai-karesabari.firebasestorage.app',
  );
}
